#docker-compose up --build
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules    #ignore this reference in container
      - .:/app
  test:  #for running the test file
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules    #ignore this reference in container
      - .:/app
    command: ["npm", "run", "test"]
